### ISSUE TITLE
Managing note information with firestore

### ISSUE THREAD

**Issue by quwen** [quwen/myblog#2]
Integrate my app with Cloud Firestore DB.

# TODO list

- [x] Add Authentication
- [x] Creation of the DB
- [x] Importing firesore to the app
- [x] Load DB data
- [x] Save to DB
- [x] Deleting DB data
